### ISSUE TITLE
get not supported

### ISSUE THREAD

**Issue by sebastiendementen** [Colin-b/requests_auth#1]
Is it possible to support the 'GET' ? I read a "Unable to properly perform authentication. GET is not supported for now." for LinkedIn OAuth2

context: I am trying to use the module for LinkedIn to manage the oauth2 in https://github.com/HootsuiteLabs/python-linkedin-v2

**Comment by Colin-b** [comment]
Can you provide a sample of code you are using to reproduce the issue?

I have a hard time finding sample of responses (I recall the token was provided as an anchor in the URL by petstore.swagger.io but their authentication server is down...)

**Comment by Colin-b** [comment]
Handled thanks to your PR
