### ISSUE TITLE
Handle refresh token

### ISSUE THREAD

**Issue by Colin-b** [Colin-b/requests_auth#13]

**Comment by StijnCaerts** [comment]
Hi, I would like to work on this feature. Are there certain things (like code structure, earlier remarks, ...) I have to keep in mind while implementing this?

**Comment by Colin-b** [comment]
Hello Stijn,

This is much appreciated, no specific remarks, feel free to work as you feel like and I will make some comments while reviewing the Pull Request in any case :)

Thanks and Regards
