### ISSUE TITLE
Default Okta Authorization server url should contain the word default

### ISSUE THREAD

**Issue by Simon-Lessage** [Colin-b/requests_auth#27]
Okta provides a pre-configured Custom Authorization Server with the name default. This default authorization server includes a basic access policy and rule, which you can edit to control access. It allows you to specify default instead of the authServerId in requests to it:

https://dev-708457.okta.com/oauth2/default/v1/authorize

**Comment by Colin-b** [comment]
Thanks for reporting. It will be part of next release
