### ISSUE TITLE
use client_id/client_secret in OAuth2ClientCredentials

### ISSUE THREAD

**Issue by sdementen** [Colin-b/requests_auth#30]
instead of username/password

**Comment by Colin-b** [comment]
As it will be a major release (breaking change), it will not be part of the upcoming release but the next one (5.0.0)

**Comment by sdementen** [comment]
Can you provide a backward compatible way? I'd accept both parameter names

**Comment by Colin-b** [comment]
The release will contains breaking changes as it drop Python support for version < 3.6

So no backward compatibility for this change, I would rather keep the code clean :)

Implemented in feature/release5 branch
