### ISSUE TITLE
add an OktaClientCredentials

### ISSUE THREAD

**Issue by sdementen** [Colin-b/requests_auth#31]
in the same spirit as `OktaImplicit(instance='testserver.okta-emea.com', authorization_server="my-auth-server", client_id='54239d18-c68c-4c47-8bdd-ce71ea1d50cd')` but for OAuth2ClientCredentials.

Today, I need to write
```
OAuth2ClientCredentials(
        authorization_url="https://my-okta-instance/oauth2/my-server/v1/authorize",
        token_url="https://my-okta-instance/oauth2/my-server/v1/token",
        username="my-client-id",
        password="my-client-secret",
        scope="my-scope",
    )
```
while I'd like to write
```
OktaClientCredentials(
        instance="my-okta-instance",
        authorization_server="my-server",
        client_id="my-client-id",
        client_secret="my-client-secret",
        scope="my-scope",
    )
```
(the change from username/password to client_id/client_secret is also in #30

**Comment by Colin-b** [comment]
@sdementen  Can you confirm that there is no authorization_url in your version and that this is a typo?

**Comment by Colin-b** [comment]
Will be part of next release

**Comment by sdementen** [comment]
Indeed, no need for authorization_url
