### ISSUE TITLE
I am trying to use requests_auth.OktaAuthorizationCode and can you please get me any example

### ISSUE THREAD

**Issue by yashcs** [Colin-b/requests_auth#48]
I am trying to use requests_auth.OktaAuthorizationCode and can you please get me any example

**Comment by Colin-b** [comment]
Hi @yashcs,

You will find a sample [on the project readme](https://github.com/Colin-b/requests_auth#okta-oauth2-authorization-code).

```python
import requests
from requests_auth import OktaAuthorizationCode


okta = OktaAuthorizationCode(instance='testserver.okta-emea.com', client_id='54239d18-c68c-4c47-8bdd-ce71ea1d50cd')
requests.get('http://www.example.com', auth=okta)
```

The parameters are listed right after the Python code sample.

You might have to set the authorization_server parameter if it's not "default" (this is the case in my current company).

If you don't know where to retrieve all those parameters (instance, client_id and authorization_server, ..) I can ask around and come back with more details on where to find them in an OKTA administration page. Do you want me to?
