### ISSUE TITLE
request a new token when token is too close to expire

### ISSUE THREAD

**Issue by sdementen** [Colin-b/requests_auth#60]
I have an issue with a token in the cache that is expiring at time T and a request sent at time T that will use this token as not yet expired. The request fails as the token, when reaching the API backend on T+some ms is expired.
It would be useful to be able to specify some delta/interval (in seconds) that would trigger a refresh of the token if it expires after this delta.
e.g. `OAuth2ClientCredentials(validity_duration=5, ...)` will request a new token if `now+5>expiry´.

**Comment by Colin-b** [comment]
Indeed that make sense, it might also be the occasion to look into #13 

I will put a default value that can be overridden if there is a need (on some slow network) but in your case it would not require any changes.

**Comment by sdementen** [comment]
What do you think for default value? 5s?

**Comment by Colin-b** [comment]
5s should cover it yes

**Comment by sdementen** [comment]
hello @Colin-b , would you have an ETA for this feature ?

**Comment by sdementen** [comment]
and/or any quick patch I could apply ?

**Comment by Colin-b** [comment]
Feel free to come up with a patch or I will try to find some time this weekend :-)

**Comment by sdementen** [comment]
hello @Colin-b , did you already work on this ?

**Comment by Colin-b** [comment]
Fixed since release 6.0.0
