### ISSUE TITLE
Debug log should not display token

### ISSUE THREAD

**Issue by sdementen** [Colin-b/requests_auth#62]
In debug mode, the logger display a message "Inserting token expiring on ..." with the complete token (https://github.com/Colin-b/requests_auth/blob/develop/requests_auth/oauth2_tokens.py#L82).

Display secret in logs is not recommended (AFAIK).
Maybe replace in the message the token by just the beginning/end of token ?

**Comment by Colin-b** [comment]
Indeed it would be better to avoid sending tokens in logs. You can submit a PR or I will have a look as soon as I can find some time, as this is for client usage and the usual TTL of a token is of a few hours I don't think it's critical right ?

**Comment by Colin-b** [comment]
Version 8.0.0 is available on pypi and fixes this issue
