### ISSUE TITLE
Limit permissions of the created token cache file

### ISSUE THREAD

**Issue by anttimaula-fsc** [Colin-b/requests_auth#71]
It would be nice if the JsonTokenFileCache() class would create the token file cache with limited permissions, for example, 

instead of:
```
with open(self.tokens_path, "w") as tokens_cache_file:
                json.dump(self.tokens, tokens_cache_file)
```

doing something like:

```
with open(os.open(self.tokens_path, os.O_WRONLY | os.O_CREAT, 0o600), "w") as tokens_cache_file:
                json.dump(self.tokens, tokens_cache_file)
```

would make the token cache file accessible for the current user only per default.

**Comment by Colin-b** [comment]
Hi @anttimaula-fsc ,

Thanks for the suggestion. I am trying to see if there is a need for the file to be accessible to other users but I don't think it would actually make sense indeed.

I am open to a pull request if you feel like it :)

Thanks again

**Comment by Colin-b** [comment]
Hello, considering the file location is up to you, You can already setup this properly yourself upfront.
I'd rather keep file system consideration and related issues outside of the scope of this package. Also it might not fit every use case.
