### ISSUE TITLE
Request for Access token from Azure function app

### ISSUE THREAD

**Issue by manojmec** [Colin-b/requests_auth#72]
from azure.identity import DefaultAzureCredential
from azure.keyvault.keys import KeyClient

credential = DefaultAzureCredential()

key_client = KeyClient(vault_url="https://my-key-vault.vault.azure.net/", credential=credential)
key = key_client.get_key("key-name")
print(key.name)

how to get the access token from Oauth 2 google analytics api from the above step

**Comment by Colin-b** [comment]
Hello @manojmec , could you please elaborate? I assume you want to connect to Google Analytics API using a key you retrieved from your Azure vault, is that correct?

Do you have some documentation on google analytics authentication? If so I could draft you a sample of code (if that is of course currently supported)

**Comment by Colin-b** [comment]
Considering we already have a ticket for this auth class and no response was received, I am closing this.
