### ISSUE TITLE
Allow to provide FQDN for localhost redirect

### ISSUE THREAD

**Issue by ManojSN** [Colin-b/requests_auth#74]
BrowserAuth currently is hardcoded to use http://localhost. Prefer to pass the request_uri_domain as a keyword arg, with default being http://localhost.

**Comment by Colin-b** [comment]
Do you mean that you have some kind of alias for localhost? The token needs to be received in some way, how would this work?

**Comment by ManojSN** [comment]
Hi Colin,

Thanks for responding, I was going to send you a PR.

The request is to allow the implementor to be able to provide a fqdn for local host.

http://localhost.somecompany.com

I just sent a PR for your initial comments

Manoj Nair



Thanks

Manoj

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ManojSN** [comment]
Hi Colin,

As for the SonarCode analysis, guessing only you can accept the risk with hardcoded http://

Manoj

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Colin-b** [comment]
Version 8.0.0 is available on pypi and fixes this issue
